#!/usr/bin/env sh

cd "$DOTFILES" || { echo "Error: Unable to navigate to $DOTFILES"; exit 1; }

# Split STOW_FOLDERS into an array
IFS=',' read -r -a folders <<< "$STOW_FOLDERS"

for folder in "${folders[@]}"; do
  echo "Removing $folder..."
  stow -D "$folder"
done

