#!/usr/bin/env sh

USR_DIRS="${USR_DIRS:-clang,ghostty,git,i3,i3-scrot,nvim,oh-my-zsh,tmux,zsh}"
SYS_DIRS="${SYS_DIRS:-bin,fonts}"
DOTFILES="${DOTFILES:-$HOME/.dotfiles}"

cd "$DOTFILES" || { echo "Error: Unable to navigate to $DOTFILES"; exit 1; }

# Split STOW_FOLDERS into an array
IFS=',' read -r -a folders <<< "$STOW_FOLDERS"

for folder in "${folders[@]}"; do
  echo "Removing $folder..."
  stow -D "$folder"
done
