#!/usr/bin/env sh

sudo pacman-mirrors --api --set-branch unstable
sudo pacman-mirrors --fasttrack 5 && sudo pacman -Syu 
sudo pacman -Syu --needed - < pkglist.txt

if ! command -v stow >/dev/null 2>&1; then
  echo "Error: GNU Stow not found in PATH."
  exit 1
fi

cd "$DOTFILES" || { echo "Error: Unable to navigate to $DOTFILES"; exit 1; }

IFS=',' read -r -a sys_dirs <<< "$SYS_DIRS"
for dir in "${sys_dirs[@]}"; do
  echo "Stowing $dir..."
  sudo stow -D -t / "$dir" 2>/dev/null
  sudo stow -t / "$dir"
done
sudo fc-cache -fv
IFS=',' read -r -a usr_dirs <<< "$USR_DIRS"
for dir in "${usr_dirs[@]}"; do
  echo "Stowing $dir..."
  stow -D "$dir" 2>/dev/null
  stow "$dir"
done

git config --global core.excludesfile ~/.gitignore_global

# pwndbg (https://github.com/pwndbg/pwndbg)
git clone https://github.com/pwndbg/pwndbg
cd pwndbg
sudo sh setup.sh
cd ~/
rm -rf pwndbg

# RTL8821 drivers for TP-Link AC600 Archer
# (https://github.com/morrownr/8821au-20210708)
# requires blackarch/pfring-dkms 1:3962.cb73329b-1

git clone https://github.com/morrownr/8821au-20210708
cd  8821au-20210708
sudo sh install-driver.sh
cd ~/
rm -rf pwndbg

