#!/usr/bin/env sh

sudo pacman-mirrors --api --set-branch unstable
sudo pacman-mirrors --fasttrack 5 && sudo pacman -Syu 
sudo pacman -Syu --needed - < pkglist.txt

if ! command -v stow >/dev/null 2>&1; then
  echo "Error: GNU Stow not found in PATH."
  exit 1
fi

cd "$DOTFILES" || { echo "Error: Unable to navigate to $DOTFILES"; exit 1; }

IFS=',' read -r -a sys_dirs <<< "$SYS_DIRS"
for dir in "${sys_dirs[@]}"; do
  echo "Stowing $dir..."
  sudo stow -D -t / "$dir" 2>/dev/null
  sudo stow -t / "$dir"
done
sudo fc-cache -fv
IFS=',' read -r -a usr_dirs <<< "$USR_DIRS"
for dir in "${usr_dirs[@]}"; do
  echo "Stowing $dir..."
  stow -D "$dir" 2>/dev/null
  stow "$dir"
done

git config --global core.excludesfile ~/.gitignore_global

# pwndbg (https://github.com/pwndbg/pwndbg)
git clone https://github.com/pwndbg/pwndbg
cd pwndbg
sudo sh setup.sh
cd ~/
rm -rf pwndbg

# BlackArch (https://www.blackarch.org/blackarch-guide-en.pdf)
echo "Downloading strap.sh..."
curl -O https://blackarch.org/strap.sh

EXPECTED_SHA1="d062038042c5f141755ea39dbd615e6ff9e23121"
echo "Verifying SHA1 checksum..."
ACTUAL_SHA1=$(sha1sum strap.sh | awk '{print $1}')

if [ "$ACTUAL_SHA1" = "$EXPECTED_SHA1" ]; then
  echo "SHA1 checksum match. Installing BlackArch Keychain..."
  sudo chmod +x strap.sh
  sudo ./strap.sh
else
  echo "Error: SHA1 checksum does not match!"
  echo "Expected: $EXPECTED_SHA1"
  echo "Actual:   $ACTUAL_SHA1"
  echo "Aborting for security reasons."
  exit 1
fi

# RTL8821 drivers for TP-Link AC600 Archer
# (https://github.com/morrownr/8821au-20210708)
# requires blackarch/pfring-dkms 1:3962.cb73329b-1

git clone https://github.com/morrownr/8821au-20210708
cd  8821au-20210708
sudo sh install-driver.sh
cd ~/
rm -rf pwndbg

