#!/usr/bin/env sh

USR_DIRS="${USR_DIRS:-clang,ghostty,git,i3,i3-scrot,nvim,oh-my-zsh,tmux,zsh}"
SYS_DIRS="${SYS_DIRS:-bin,fonts}"
DOTFILES="${DOTFILES:-$HOME/.dotfiles}"
REPO_URL="https://github.com/flinnthebin/dotfiles"

if [ -d "$DOTFILES" ]; then
    echo ".dotfiles found. Pulling the latest changes..."
    git -C "$DOTFILES" pull
else
    echo ".dotfiles not found. Cloning repository..."
    mkdir -p "$DOTFILES"
    git clone "$REPO_URL" "$DOTFILES"
fi

echo "Installing..."

sudo pacman -Scc
sudo pacman -Sy archlinux-keyring manjaro-keyring
sudo pacman -S linux66 linux66-headers
sudo pacman -S linux615-headers
reboot
