#!/usr/bin/env sh

DOTFILES="${DOTFILES:-$HOME/.dotfiles}"
REPO_URL="https://github.com/flinnthebin/dotfiles"

if [ -d "$DOTFILES" ]; then
    echo ".dotfiles found. Pulling the latest changes..."
    git -C "$DOTFILES" pull
else
    echo ".dotfiles not found. Cloning repository..."
    mkdir -p "$DOTFILES"
    git clone "$REPO_URL" "$DOTFILES"
fi

echo "Installing..."

sudo pacman -Scc
sudo pacman -Sy archlinux-keyring manjaro-keyring
sudo pacman -S linux-meta
sudo pacman -Syyu
reboot
