#!/usr/bin/env sh

DOTFILES="${DOTFILES:-$HOME/.dotfiles}"
REPO_URL="https://github.com/flinnthebin/dotfiles"

if [ -d "$DOTFILES" ]; then
    echo ".dotfiles found. Pulling the latest changes..."
    git -C "$DOTFILES" pull
else
    echo ".dotfiles not found. Cloning repository..."
    mkdir -p "$DOTFILES"
    git clone "$REPO_URL" "$DOTFILES"
fi

echo "Installing..."

# update packages
sudo pacman-mirrors --api --set-branch unstable
sudo pacman-mirrors --fasttrack 5 && sudo pacman -Syu
sudo pacman -Syu --needed - < ~/.dotfiles/pkglist.txt

# get audio working
systemctl --user enable --now pipewire pipewire-pulse

# git
git config --global core.excludesfile ~/.gitignore_global
git config --global user.email "christopher.flinn@gmail.com"
git config --global user.name "Chris Flinn"

# oh-my-zsh
# Required for config files
# Python venv
python3 -m venv "$HOME/.pynv"

# Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# pwndbg (https://github.com/pwndbg/pwndbg)
git clone https://github.com/pwndbg/pwndbg ~/.pwndbg
cd ~/.pwndbg
sudo sh setup.sh
echo "source ~/.pwndbg/gdbinit.py" > ~/.gdbinit
cd ~/

# RTL8821 drivers for TP-Link AC600 Archer
# (https://github.com/morrownr/8821au-20210708)
# requires blackarch/pfring-dkms 1:3962.cb73329b-1
yay -S rtl8812au-dkms-git

# GNU Typist
yay -S gtypist

# Hardened Firefox
firefox # (generate ~/.mozilla)
sleep 2
wget -O "$(find ~/.mozilla/firefox -maxdepth 1 -type d -name '*.default-release')/user.js" https://raw.githubusercontent.com/arkenfox/user.js/refs/heads/master/user.js

# oh-my-zsh (sets zsh as default shell)
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# requires manual reboot
