#!/usr/bin/env bash

DOTFILES="${DOTFILES:-$HOME/.dotfiles}"
REPO_URL="https://github.com/flinnthebin/dotfiles"

if [ -d "$DOTFILES" ]; then
    echo ".dotfiles found. Pulling the latest changes..."
    git -C "$DOTFILES" pull
else
    echo ".dotfiles not found. Cloning repository..."
    mkdir -p "$DOTFILES"
    git clone "$REPO_URL" "$DOTFILES"
fi

echo "Installing..."

export DEBIAN_FRONTEND=noninteractive
sudo apt update
sudo apt install -y linux-image-amd64 linux-headers-amd64
sudo apt install kali-linux-everything
sudo apt -y full-upgrade
sudo apt -y autoremove --purge
sudo apt autoclean
sudo apt clean
sudo reboot
